### ISSUE TITLE
Broken after the new update of discord

### ISSUE THREAD

**Issue by GTREDITION** [BleedingBD/plugin-NoReplyPing#2]
![imagen](https://github.com/BleedingBD/plugin-NoReplyPing/assets/53015599/b97458e4-ad48-4c49-bd06-2b40c62db11a)

**Comment by Drflash55** [comment]
Can confirm that #3 fixed the issue by manually implementing the updates into the plugin.

Will just have to wait until the author makes the changes on their page.

**Comment by QbDesu** [comment]
@TheKodeToad's fix was merged and should be available via BD's plugin update mechanisms soon-ish.
